### ISSUE TITLE
Which license is this code released under

### ISSUE THREAD

**Issue by specious** [adnanrahic/serverless-docker-image-resize#10]
I'm borrowing some technical ideas from the [article](https://hackernoon.com/a-crash-course-on-serverless-with-aws-image-resize-on-the-fly-with-lambda-and-s3-850be95d5833) you have published, as I'm working on implementing a very similar on-the-fly image scaling capability in this project:

https://github.com/earthstewards/littermap-aws-backend/issues/2

I'm specifically looking for a solution where the image stream is continuously processed and the resulting stream pushed to its destination right as it's downloading the source image data.

This repository doesn't appear to mention an open source license, so I'd like to inquire which license you're sharing this code under.

**Comment by adnanrahic** [comment]
Hey! Thanks for asking. I've just added #11 to solve this issue. Best of luck!
