### ISSUE TITLE
HTTPS image access

### ISSUE THREAD

**Issue by abelland** [adnanrahic/serverless-docker-image-resize#3]
Feature Request: Allow an user to access images via HTTPS

Example:
http://$BUCKET.s3-website.$REGION.amazonaws.com/700x700/ab.jpeg
to
**https**://$BUCKET.s3-website.$REGION.amazonaws.com/700x700/ab.jpeg

Any chance?

**Comment by adnanrahic** [comment]
The only way to do it is to configure the bucket website to point to your own domain which has an SSL certificate. This is a great issue. I know of a few ways of implementing it easily, and will definitely have a look at it next week.

Until then, check [this](https://docs.aws.amazon.com/AmazonS3/latest/dev/website-hosting-custom-domain-walkthrough.html#website-hosting-custom-domain-walkthrough-domain-registry) out. You'll learn how to set up a custom domain for an S3 bucket website. From there you need to have an SSL certificate, and hey presto, that's it. [Here's a tutorial](https://medium.com/@sbuckpesch/setup-aws-s3-static-website-hosting-using-ssl-acm-34d41d32e394) for that as well. :smile:

**Comment by abelland** [comment]
I will definitely give it a try. Thanks 👍

**Comment by adnanrahic** [comment]
Did you manage to get it working?
